jms_serializer:
    enum_support: true
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'

    handlers:
        datetime:
            default_format:   "Y-m-d\\TH:i:sP" # ATOM
            default_timezone: "UTC"
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    default_context:
        serialization:
            serialize_null: true
        deserialization:
            serialize_null: true
