security:
    password_hashers:
        harsh:
            algorithm: auto
            memory_cost: 4092
            time_cost: 10
    providers:
        users:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/public/login$
            stateless: true
            json_login:
                check_path: /public/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        documentation:
            pattern: ^/documentation$
            security: false
        documentation_json:
            pattern:  ^/documentation.json$
            security: false
        public:
            pattern: ^/public/
            security: false
        main:
            stateless: true
            entry_point: jwt
            provider: users
            jwt: ~
            refresh_jwt:
                check_path: /public/login/refresh

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/login/refresh$, roles: PUBLIC_ACCESS }
        - { path: ^/reset_password$, roles: PUBLIC_ACCESS }
        - { path: ^/medias/, roles: PUBLIC_ACCESS }
        - { path: ^/public/, roles: PUBLIC_ACCESS }
        - { path: ^/,       roles: [ IS_AUTHENTICATED_FULLY, ROLE_USER ] }

    role_hierarchy:
        ROLE_CUSTOMER: [ ROLE_USER ]
        ROLE_MONITOR: [ ROLE_USER ]
        ROLE_ADMIN: [ ROLE_USER, ROLE_MONITOR ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
