version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: symfony-app
      # You should definitely change the password in production
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
