controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# JWT refresh token configuration
api_refresh_token:
    path: /public/login/refresh
